Added toast message for users to login on wishcards and homepage
stacysealky/donategifts pull request #102
Opened 2020-10-23 14:25 UTC by deep-a

2020-10-23 16:03 UTC, Enubia requested changes

2020-10-23 16:03 UTC, Enubia commented on client/views/home.ejs
> +      setTimeout(function() {<% if (!locals.user) { %>
I'd move the script to an own file and just reference it from there if you need to call the script twice

2020-10-23 16:08 UTC, gnorbsl commented
whats with all the changes in the package-lock? looks like a few packages are downgraded there.

can you get the latest master and run npm install

2020-10-27 17:53 UTC, stacysealky commented
Is this all good to merge now? @deep-a @gnorbsl

2020-10-27 20:21 UTC, gnorbsl commented
No it srill requires changes and he has to merge latest changes into his branch too

2020-10-27 22:05 UTC, deep-a commented
@Enubia would something like this be better?
```
<% if (!locals.user) { %>
  <script src="/public/clientJS/loginToast.js"></script>
<% } %>
```

2020-10-28 06:40 UTC, Enubia commented
please fix the package-lock file once more @deep-a

2020-10-29 04:06 UTC, Enubia approved these changes

2020-10-31 12:23 UTC, gnorbsl approved these changes

2020-10-31 12:23 UTC, merged

2020-10-31 22:13 UTC, stacysealky commented
good to merge now? @Enubia @deep-a