refactor: new project structure, db repositories
stacysealky/donategifts pull request #69
Opened 2020-10-16 21:05 UTC by Enubia

2020-10-16 21:36 UTC, stacysealky commented
Wow, thanks for cleaning! it was much needed. 
Just make sure that we are linking all static assets from the changed directories, etc.  
I haven't fully reviewed this, but I think the chooseItem.ejs and defaultItems.js use all local img assets. So make sure they are still linked please. 

@gnorbsl please review this PR thanks

2020-10-16 21:48 UTC, gnorbsl requested changes

2020-10-16 21:48 UTC, gnorbsl commented on listtree.sh
> +#!/bin/bash
I assume this is a leftover from your structure template?

2020-10-16 21:48 UTC, gnorbsl commented on nodemon.json
> +  "exec": "NODE_ENV=development node --inspect=0.0.0.0:9229 server/app.js"
this might break takikkos setup, NODE_ENV dev should be filled automatically on startup by dotenv

2020-10-16 21:48 UTC, gnorbsl commented on projectStructure.md
> +## Project structure
I think this can be removed?

2020-10-16 21:48 UTC, gnorbsl commented on server/routes/users.js
> +    res.status(200).render(path.join(__dirname, '../../client/views/home'), {
those are not neccessary, we just have to tell ejs where the views are, itll get the correct ones then

2020-10-17 20:23 UTC, gnorbsl approved these changes

2020-10-17 20:24 UTC, merged

2020-10-17 20:24 UTC, gnorbsl commented
lets hope I wont regret this